"use client";
import { useI18n } from "@/components/LocaleProvider";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { TaskSeries } from "@prisma/client";
import { createFlexibleSeries,stopFlexibleSeries,applyTaskBundle } from "@/app/actions/planning-options";
import { TASK_BUNDLES } from "@/lib/templates";
import { ActionButton } from "./ActionButton";
export function FlexibleTasks({ today, series }: { today:string;series:TaskSeries[] }) {
  const { t } = useI18n();
 const [message,setMessage]=useState(""),[pending,setPending]=useState(false),[frequency,setFrequency]=useState("WEEKLY");const router=useRouter();
 async function submit(e:React.FormEvent<HTMLFormElement>,action:typeof createFlexibleSeries|typeof applyTaskBundle){e.preventDefault();const data=new FormData(e.currentTarget);setPending(true);try{const result=await action(data);setMessage(result.error??t("Guardado. Las tareas aparecen al abrirse su ventana de cumplimiento."));if(!result.error)router.refresh();}catch{setMessage(t("No se pudo guardar."));}finally{setPending(false);}}
 return <section className="space-y-5 rounded-2xl border border-line bg-card p-5"><h2 className="text-xl">{t("Tareas recurrentes flexibles")}</h2><p className="text-xs text-muted">{t("Una tarea por periodo, con fecha de apertura y límite. El motor busca un hueco dentro de su ventana, sin fijar una cita.")}</p><form aria-busy={pending} className="grid gap-3 text-sm" onSubmit={e=>submit(e,createFlexibleSeries)}><label>{t("Tarea")}<input name="title" maxLength={160} required className="field" placeholder={t("Pagar la luz, revisar copias…")} /></label><div className="grid grid-cols-2 gap-3"><label>{t("Minutos")}<input name="durationMinutes" type="number" min={5} max={480} defaultValue={20} required className="field" /></label><label>{t("Prioridad")}<select name="priority" defaultValue="2" className="field"><option value="1">{t("Alta")}</option><option value="2">{t("Media")}</option><option value="3">{t("Baja")}</option></select></label></div><label>{t("Repetición")}<select name="frequency" value={frequency} onChange={e=>setFrequency(e.target.value)} className="field"><option value="WEEKLY">{t("Cada semana")}</option><option value="MONTHLY">{t("Cada mes")}</option></select></label><label>{t("Primera apertura")}<input name="anchorDate" type="date" defaultValue={today} required className="field" /></label><label>{t("Ventana para cumplir · días")}<input name="windowDays" type="number" min={1} max={frequency==="WEEKLY"?7:31} defaultValue={7} required className="field" /></label><p className="text-xs text-muted">{t("Elige un viernes como primera apertura para repetir cada viernes. Una apertura mensual en el día 31 se adapta al último día en meses cortos.")}</p><input name="preferredWindow" type="hidden" value="ANY" /><input name="energy" type="hidden" value="LIGHT" /><button disabled={pending} className="rounded-full border border-line px-4 py-2">{t("Crear repetición flexible")}</button></form>
 {series.length>0&&<ul className="space-y-3 border-t border-line pt-4 text-sm">{series.map(s=><li key={s.id}><p>{s.title} · {s.frequency==="WEEKLY"?t("Semanal"):t("Mensual")} {t(" · ventana de ")}{s.windowDays} {t(" días")}</p><div className="mt-2"><ActionButton action={stopFlexibleSeries.bind(null,s.id)} confirm={t("¿Detener futuras repeticiones? Se conservan las tareas de ventanas ya abiertas y los bloques fijados o empezados.")}>{t("Detener repetición")}</ActionButton></div></li>)}</ul>}
 <form aria-busy={pending} onSubmit={e=>submit(e,applyTaskBundle)} className="space-y-3 border-t border-line pt-4 text-sm"><h3 className="text-lg">{t("Plantillas de tareas")}</h3><label className="block">{t("Plantilla")}<select name="template" className="field">{TASK_BUNDLES.map(template=><option key={template.key} value={template.key}>{t(template.title)}</option>)}</select></label><label className="block">{t("Fecha del viaje o entrega")}<input name="date" type="date" min={today} defaultValue={today} required className="field" /></label><p className="text-xs text-muted">{t("Crea varias tareas con plazos relativos a esa fecha. Puedes editarlas después; si una fecha ya pasó, se mostrará en riesgo.")}</p><button disabled={pending} className="rounded-full border border-line px-4 py-2">{t("Crear tareas de la plantilla")}</button></form>{message&&<p role="status" className="text-sm text-sage">{t(message)}</p>}</section>;
}
