"use client";
import { displayClock } from "@/lib/locale";
import { useI18n } from "@/components/LocaleProvider";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { DayOverride } from "../generated/prisma/client";
import { saveException, removeException, applyWeekTemplate } from "@/app/actions/planning-options";
import { WEEK_TEMPLATES } from "@/lib/templates";
import { ActionButton } from "./ActionButton";
export function PlanningExceptions({ today, monday, rows }: { today: string; monday: string; rows: DayOverride[] }) {
  const { t, preferences } = useI18n();
 const [message,setMessage]=useState(""),[pending,setPending]=useState(false);const router=useRouter();
 async function submit(event: React.FormEvent<HTMLFormElement>, action: typeof saveException | typeof applyWeekTemplate) {event.preventDefault();const data=new FormData(event.currentTarget);setPending(true);try{const result=await action(data);setMessage(result.error??t("Calendario temporal guardado. Los bloques flexibles futuros se organizarán de nuevo; se mantienen citas y bloques iniciados."));if(!result.error)router.refresh();}catch{setMessage(t("No se pudo guardar."));}finally{setPending(false);}}
 return <section className="space-y-5 rounded-2xl border border-line bg-card p-5"><h2 className="text-2xl">{t("Vacaciones y días especiales")}</h2><p className="text-sm text-muted">{t("Pausa el planificador o cambia el horario de fechas concretas. Tu horario base se conserva; los bloques flexibles futuros del rango vuelven a quedar pendientes.")}</p>
 <form aria-busy={pending} onSubmit={e=>submit(e,saveException)} className="grid gap-3 text-sm sm:grid-cols-2"><label>{t("Desde")}<input name="start" type="date" min={today} defaultValue={today} required className="field" /></label><label>{t("Hasta")}<input name="until" type="date" min={today} defaultValue={today} required className="field" /></label><label>{t("Nombre")}<input name="label" maxLength={80} placeholder={t("Vacaciones, festivo…")} className="field" /></label><label>{t("Qué hacer")}<select name="mode" className="field"><option value="PAUSE">{t("Pausar planificador")}</option><option value="HOURS">{t("Usar un horario temporal")}</option></select></label><label>{t("Inicio temporal")}<input name="startTime" type="time" defaultValue="09:00" required className="field" /></label><label>{t("Fin temporal")}<input name="endTime" type="time" defaultValue="13:00" required className="field" /></label><button disabled={pending} className="rounded-full border border-line px-4 py-2 sm:col-span-2">{t("Aplicar a estas fechas")}</button></form>
 <form aria-busy={pending} onSubmit={e=>submit(e,applyWeekTemplate)} className="space-y-3 border-t border-line pt-4 text-sm"><h3 className="text-lg">{t("Plantilla de semana")}</h3><label className="block">{t("Inicio de una semana futura")}<input name="date" type="date" min={today} defaultValue={monday} required className="field" /></label><label className="block">{t("Semana tipo")}<select name="template" className="field">{WEEK_TEMPLATES.map(template=><option key={template.key} value={template.key}>{t(template.title)}</option>)}</select></label><p className="text-xs text-muted">{t("Aplica lunes a viernes y pausa sábado y domingo. Sustituye las excepciones de esa semana, conservando la configuración base.")}</p><button disabled={pending} className="rounded-full border border-line px-4 py-2">{t("Aplicar semana tipo")}</button></form>
 {message&&<p role="status" className="text-sm text-sage">{t(message)}</p>}
 <details><summary className="text-sm text-muted">{t("Próximas excepciones (")}{rows.length})</summary><ul className="mt-3 space-y-3 text-sm">{rows.map(row=><li key={row.id} className="flex flex-wrap items-center justify-between gap-2"><span>{row.date.toISOString().slice(0,10)} · {row.label??t("Día especial")} · {row.paused?t("Pausado"):row.startTime?`${displayClock(row.startTime, preferences)}–${displayClock(row.endTime!, preferences)}`:t(`Capacidad ${row.capacityPercent} %`)}{row.essentialOnly?t(" · solo esenciales y urgentes"):""}</span><ActionButton action={removeException.bind(null,row.id)}>{t("Restaurar horario base")}</ActionButton></li>)}</ul></details></section>;
}
