"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { savePreferences } from "@/app/actions/preferences";
import { useI18n } from "./LocaleProvider";
export function RegionalPreferences() {
  const { preferences, t } = useI18n(); const router = useRouter();
  const [message, setMessage] = useState(""); const [pending, setPending] = useState(false); const [failed, setFailed] = useState(false);
  return <section className="rounded-2xl border border-line bg-card p-5"><h2 className="text-2xl">{t("Idioma y calendario")}</h2><p className="mt-2 text-sm text-muted">{t("Se guarda en tu cuenta y se aplica en todos tus dispositivos. Cambiar el primer día recalcula las cuotas semanales y libera sus bloques flexibles futuros; se conserva el historial.")}</p><form key={JSON.stringify(preferences)} aria-busy={pending} className="mt-4 flex flex-wrap items-end gap-4" onSubmit={async e => { e.preventDefault(); setPending(true); setMessage(""); try { const result = await savePreferences(new FormData(e.currentTarget)); setFailed(Boolean(result.error)); setMessage(result.error ?? t("Preferencias guardadas.")); if (!result.error) router.refresh(); } catch { setFailed(true); setMessage(t("No se pudo guardar. Inténtalo de nuevo.")); } finally { setPending(false); } }}><label>{t("Idioma")}<select name="locale" defaultValue={preferences.locale} className="field"><option value="es">Español</option><option value="en">English</option></select></label><label>{t("Formato de hora")}<select name="hourFormat" defaultValue={preferences.hourFormat} className="field"><option value="24">{t("24 horas")}</option><option value="12">{t("12 horas · AM/PM")}</option></select></label><label>{t("Primer día de la semana")}<select name="weekStartsOn" defaultValue={preferences.weekStartsOn} className="field"><option value="1">{t("Lunes")}</option><option value="0">{t("Domingo")}</option></select></label><button disabled={pending} className="rounded-full bg-sage px-4 py-3 text-white">{t(pending ? "Guardando…" : "Guardar preferencias")}</button>{message && <p role={failed ? "alert" : "status"} className="w-full text-sm">{t(message)}</p>}</form></section>;
}
