ALTER TABLE "NotificationSettings" ADD COLUMN "quietEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "quietStart" TEXT NOT NULL DEFAULT '22:00',
ADD COLUMN "quietEnd" TEXT NOT NULL DEFAULT '08:00';
ALTER TABLE "Event" ADD COLUMN "planningReason" TEXT;
ALTER TABLE "WorkerRun" ADD COLUMN "kind" TEXT NOT NULL DEFAULT 'PLAN';
